import { compose, withState } from 'recompose';

import GridView from './GridsView';
const D1Icon = require('../../../assets/images/D1.jpg');
const D2Icon = require('../../../assets/images/D2.jpg');
const D3Icon = require('../../../assets/images/D3.jpg');
const D4Icon = require('../../../assets/images/D4.jpg');
const D5Icon = require('../../../assets/images/D5.jpg');
const D6Icon = require('../../../assets/images/D6.jpg');
const D7Icon = require('../../../assets/images/D7.jpg');
const D8Icon = require('../../../assets/images/D8.jpg');
const D9Icon = require('../../../assets/images/D9.jpg');
const D10Icon = require('../../../assets/images/D10.jpg');

const listData = [
  {
    id: 1,
    brand: '',
    title: '0-Dig Deeper',
    subtitle: '',
    price: '',
    badge: 'NEW',
    badgeColor: '#3cd39f',
    image: D1Icon,
    url: "index.html",
  },
  {
    id: 2,
    brand: '',
    title: '1-Fit Test',
    subtitle: '',
    price: '',
    priceFrom: true,
    image: D1Icon,
    url: "index1.html",
  },
  {
    id: 3,
    brand: '',
    title: '2-Plyometric Cardio Circuit',
    subtitle: '',
    price: '',
    priceFrom: true,
    badge: 'SALE',
    badgeColor: '#ee1f78',
    image: D2Icon,
    url: "index2.html",
  },
  {
    id: 4,
    brand: '',
    title: '3-Cardio Power&Resistance',
    subtitle: '',
    price: '',
    badge: '',
    badgeColor: 'green',
    image: D3Icon,
    url: "index3.html",
  },
  {
    id: 5,
    brand: '',
    title: '4-Cardio Recovery',
    subtitle: '',
    price: '',
    priceFrom: true,
    image: D4Icon,
    url: "index4.html",
  },
  {
    id: 6,
    brand: 'Mad Perry',
    title: '5-Pure Cardio',
    subtitle: 'Office, prom or special parties is all dressed up',
    price: '',
    priceFrom: true,
    badge: 'SALE',
    badgeColor: 'red',
    image: D5Icon,
    url: "index5.html",
  },
  {
    id: 7,
    brand: '',
    title: '6-Cardio Abs',
    subtitle: '',
    price: '',
    badge: '',
    badgeColor: '#3cd39f',
    image: D1Icon,
    url: "index6.html",
  },
  {
    id: 8,
    brand: '',
    title: '7-Core Cardio&Balance',
    subtitle: '',
    price: '',
    priceFrom: true,
    image: D7Icon,
    url: "index7.html",
  },
  {
    id: 9,
    brand: '',
    title: '8-Max Interval Circuit',
    subtitle: '',
    price: '$29.99',
    priceFrom: true,
    badge: 'SALE',
    badgeColor: '#ee1f78',
    image: D8Icon,
    url: "index8.html",
  },
  {
    id: 10,
    brand: '',
    title: '9-Max Interval Plyo',
    subtitle: '',
    price: '',
    badge: '',
    badgeColor: 'green',
    image: D9Icon,
    url: "index9.html",
  },
  {
    id: 11,
    brand: '',
    title: '10-Max Cardio Conditioning',
    subtitle: '',
    price: '',
    priceFrom: true,
    image: D10Icon,
    url: "index10.html",
  },
  {
    id: 12,
    brand: 'Mad Perry',
    title: '11-Max Recovery',
    subtitle: 'Office, prom or special parties is all dressed up',
    price: '$29.99',
    priceFrom: true,
    badge: 'SALE',
    badgeColor: 'red',
    image: D4Icon,
    url: "index11.html",
  },
  {
    id: 13,
    brand: 'Mad Perry',
    title: '12-Insane Abs',
    subtitle: 'Office, prom or special parties is all dressed up',
    price: '$29.99',
    priceFrom: true,
    badge: 'SALE',
    badgeColor: 'red',
    image: D6Icon,
    url: "index12.html",
  },
  {
    id: 14,
    brand: 'Mad Perry',
    title: '13-Max Interval Sports Training',
    subtitle: 'Office, prom or special parties is all dressed up',
    price: '$29.99',
    priceFrom: true,
    badge: 'SALE',
    badgeColor: 'red',
    image: D10Icon,
    url: "index13.html",
  },
];

export default compose(
  withState('tabIndex', 'setTabIndex', 0),
  withState('tabs', 'setTabs', ['All Video']),
  withState('data', 'setData', listData),
)(GridView);
